### ISSUE TITLE
[HELP WANTED]: Can anyone tell me what is the job limit that we need to apply daily.

### ISSUE THREAD

**Issue by deekshithsagar73** [AIHawk-co/Auto_Jobs_Applier#469]
### Issue description

Can we track how many Jobs we applied. I got rate limited by linkedin and system is saying to retry after 24 hrs . Can we add Job Limit and tracking How many Number of Jobs it applied? Although there is a success json IT is not helpful

**Comment by queukat** [comment]
@feder-cr move this to future development

**Comment by cjbbb** [comment]
fixed. you can try to fetch the new main branch, and you will see it in data_folder/output/success.json @deekshithsagar73
