### ISSUE TITLE
[BUG]: Remote true - leads to apply only Remote Jobs

### ISSUE THREAD

**Issue by surapuramakhil** [AIHawk-co/Auto_Jobs_Applier#471]
### Describe the bug

As per docs it says remote true - will also include remote jobs but we run AI Hawk it only applying for remote positions.

### Branch

None

**Comment by cjkrolak** [comment]
Remote option should be changed to a pick multiple with 3 choices, Remote, On-Site, and Hybrid.  Does anyone know if this is a documentation error or implementation error?

**Comment by cjbbb** [comment]
Fixed. Thx @surapuramakhil
