### ISSUE TITLE
[HELP WANTED]: Runtime error: Error running the bot: 'exam'

### ISSUE THREAD

**Issue by JWHu1-cmyk** [AIHawk-co/Auto_Jobs_Applier#488]
### Issue description

when I run the command to auto apply to jobs, I run into issue with AIHawk not running at all due to aforementioned error.

**Comment by LasyShark** [comment]
exam: ""

**Comment by cjbbb** [comment]
@JWHu1-cmyk could you please try to use the new "main branch". If still now work, just let me know. (please make sure you install the requirement.txt successfully)
