### ISSUE TITLE
[BUG]: <Bot doesn't run my personal resume>

### ISSUE THREAD

**Issue by Leof137** [AIHawk-co/Auto_Jobs_Applier#525]
### Describe the bug

\Auto_Jobs_Applier_AIHawk>python main.py --resume xxx_resume.pdf After lauching this, the script simply doesn't do anything. anybody with similar issue?

### Steps to reproduce

\Auto_Jobs_Applier_AIHawk>python main.py --resume xxx_resume.pdf 

- nothing

### Expected behavior

to run the script and open the page with Linkedin

### Actual behavior

nothing

### Branch

None

### Python version

3.10.10

### LLM Used

ChatGPT

### Model used

GPT-4o-mini

**Comment by feder-cr** [comment]
@Leof137 join in our telegram group https://t.me/AIhawkCommunity
