### ISSUE TITLE
[HELP WANTED]: Cannot run project on Chromebook

### ISSUE THREAD

**Issue by wongcykaren** [AIHawk-co/Auto_Jobs_Applier#533]
### Issue description

I cannot run the project on my Chromebook. The chromedriver expects linux64 but my Chromebook is run on arm architecture:

Architecture:             aarch64
  CPU op-mode(s):         32-bit, 64-bit
  Byte Order:             Little Endian
  CPU(s):                   8
  On-line CPU(s) list:    0-7
  Vendor ID:                ARM
  Model name:             Cortex-A55

Any suggestion or help? Thank you.

**Comment by feder-cr** [comment]
@wongcykaren join in our telegram group https://t.me/AIhawkCommunity
