### ISSUE TITLE
[FEATURE]: Improving Hawk to understand Job requirements and apply to them accordingly

### ISSUE THREAD

**Issue by surapuramakhil** [AIHawk-co/Auto_Jobs_Applier#538]
### Feature summary

Evalauate Job requirements & apply only if profile matches. have some hard requirements like years of experience & some soft like work ex in particular minor areas

### Feature description

making it more context are in deciding whether to apply for a job or not.

like understanding Job requirements - skip that job based on details in your resume.

### Motivation

problem is it has applied to role which requires 10+ years of experience me being at mid-level

**Comment by mdgjohnny** [comment]
Have you tried tweaking the settings (specifically, **experienceLevel**) in `config.yaml`?

**Comment by sonicnerd14** [comment]
The bot also doesn't seem to understand fields that ask questions like "How many years do you have in 'such and such'?". It just puts a year which will not work. Often this prevents an application from even being submitted and it doesn't even do a basic calculation such as taking the difference between your stated start and end dates in academics or previous job history to determine an accurate number.

**Comment by surapuramakhil** [comment]
Another use case is visa sponsorship. for some jobs they explicitly mention - "Applicant should not require visa sponsorhip" being smart, Hawk should mark No only to those specific roles. In the case of F1 or other EAD they do have temp EAD's and sponsorship would be for future.
