### ISSUE TITLE
[BUG]: It is looking for remote jobs only if remote to set true in config.yaml

### ISSUE THREAD

**Issue by sfcheng** [AIHawk-co/Auto_Jobs_Applier#551]
### Steps to reproduce

It is looking for remote jobs only if I set remote to true in config.yaml. 

This part of code has issue:

    def get_base_search_url(self, parameters):
        logger.debug("Constructing base search URL")
        url_parts = []
        if parameters['remote']:
            url_parts.append("f_CF=f_WRA")

### Expected behavior

It should look in-person and hybrid and remote jobs

### Actual behavior

remote jobs only

### Branch

main

**Comment by Vontux** [comment]
yep, still having this issue:

llm_model_type: gemini
llm_model: 'gemini-1.5-flash-8b'

**Comment by cjbbb** [comment]
fixed with #621. Thx
