### ISSUE TITLE
[BUG]: Cannot get the bot to run with either --resume or YAML mode

### ISSUE THREAD

**Issue by rosenfj1** [AIHawk-co/Auto_Jobs_Applier#666]
### Describe the bug

Neither mode works and there is no clear idea how to fix the YAML

### Steps to reproduce

plain_text_resume.yaml:
personal_information:
  name: Jeffrey
  surname: Rosenfeld
  date_of_birth: 10/06/1979
  country: United States
  city: Bergenfield
  address: 69 Wilbur Road
  zip_code: '07621'
  phone_prefix: jeffrey.rosenfeld@gmail.com
  phone: 917-664-8374
  email: jeffrey.rosenfeld@gmail.com
  linkedin: 'https://www.linkedin.com/in/jeffrosenfeld/'
education_details:
  - education_level: MBA
    institution: Rutgers University
    field_of_study: Business
    start_date: "2021"
    year_of_completion: "2024"
  - education_level: Doctoral Degree
    institution: NYU
    field_of_study: Biology
    start_date: "2005"
    year_of_completion: "2009'

experience_details:
  - position: 'Executive Director, Genomics and Bioinformatics'
    company: Tonix Pharmaceuticals
    employment_period: 2022-2024
    location: 'Chatham, NJ'
    industry: Pharmaceuticals
    key_responsibilities:
    - responsibility: "Managed team of Researchers and Consultants to perform Genome and Exome sequencing for clinical trials"
    - responsibility: "Planned, executed, and scaled research strategy"
    - responsibility_3personal_information:
  name: Jeffrey
  surname: Rosenfeld
  date_of_birth: 10/06/1979
  country: United States
  city: Bergenfield
  address: 69 Wilbur Road
  zip_code: '07621'
  phone_prefix: jeffrey.rosenfeld@gmail.com
  phone: 917-664-8374
  email: jeffrey.rosenfeld@gmail.com
  linkedin: 'https://www.linkedin.com/in/jeffrosenfeld/'
education_details:
  - education_level: MBA
    institution: Rutgers University
    field_of_study: Business
    start_date: "2021"
    year_of_completion: "2024"
  - education_level: Doctoral Degree
    institution: NYU
    field_of_study: Biology
    start_date: "2005"
    year_of_completion: "2009'

experience_details:
  - position: 'Executive Director, Genomics and Bioinformatics'
    company: Tonix Pharmaceuticals
    employment_period: 2022-2024
    location: 'Chatham, NJ'
    industry: Pharmaceuticals
    key_responsibilities:
    - responsibility: "Managed team of Researchers and Consultants to perform Genome and Exome sequencing for clinical trials"
    - responsibility: "Planned, executed, and scaled research strategy"
    - responsibility: "Developed and implemented novel multi-marker GWAS algorithms for genome enhanced clinical trials"
    - responsibility: "Administered the Identification of genomic markers that predispose patients for fibromyalgia"
    - responsibility: "Oversaw the identification of 20 SNP pharmacogenomics panel to identify patients that will respond to therapy"
    - responsibility: "Presented results weekly to the CEO and CMO"
    - responsibility: "Sourced, selected, and managed vendors, consultants and Contract Research Organizations"
    
  - position: Associate Professor of Pathology – Precision Medicine
    company: Rutgers University - Cancer Institute of NJ
    employment_period: 2011-2022
    location: 'New Brunswick, NJ'
    industry: Laboratory Testing
    key_responsibilities:
    - responsibility_1: "Supervised a team of Researchers enabling genomics, cheminformatics and digital pathology"
    - responsibility_2: "Served as Bioinformatics Lead on implementation of 3 CLIA/CAP certified solid tumor and myeloid panels"
    - responsibility_3: "Handled all aspects of sequencing projects from experimental design through analysis, and publication"
    - responsibility_4: "Developed a Machine Learning model to predict the source organ of tumors of unknown origin"
    - responsibility_5: "Awarded $100k TechAdvance grant for single-ce'll sperm sequencing of families with autistic children"
    - responsibility_6: "Co-investigator or consultant on over $2M worth of grants from NIH and the Department of Defense"
    - responsibility_7: Managed Cancer Precision Medicine data from Foundation Medicine"
  - position: President
    company: Rosenfeld Consulting
    employment_period: 2013-present
    location: New Jersey
    industry: Consulting
    key_responsibilities:
    - responsibility_1: "Comapred the Economics of ambient storage and the use of freezers for nucleic acid storage"
    - responsibility_2: "Advised executive leadership by participating in hundreds of phone calls, providing insights on bioinformatics,genomics, lab testing, and precision medicine as well-regarded expert and KOL"
    - responsibility_3: "Provided technical due diligence and advised on $70M investment in MissionBio, among other investment"
    - responsibility_4: "Expert witness for the BRCA1 patent litigation, providing insights into genomic aspects of the litigation"
  - position: Research Scientist
    company: Northwell Health
    employment_period: 2009-2011
    location: 'Queens, NY'
    industry: Basic Research
    key_responsibilities:
    - responsibility_1: "Conducted analysis of GWAS and exome sequencing data for schizophrenia"
    - responsibility_2: "Designed and integrated a framework to identify multi-nucleotide polymorphisms in genomes
    - responsibility_3: Recipient of NARSAD Young Investigator Grant
languages:
  - language: English
    proficiency: Native

availability:
  notice_period: 2 weeks
self_identification:
  gender: '[Gender]'
  pronouns: '[Pronouns]'
  veteran: '[No]'
  disability: '[No]'
  ethnicity: '[Caucasian]'
legal_authorization:
  eu_work_authorization: '[No]'
  us_work_authorization: '[Yes]'
  requires_us_visa: '[No]'
  requires_us_sponsorship: '[Yes]'
  requires_eu_visa: '[Yes]'
  legally_allowed_to_work_in_eu: '[No]'
  legally_allowed_to_work_in_us: '[Yes]'
  requires_eu_sponsorship: '[Yes]'
  canada_work_authorization: '[No]'
  requires_canada_visa: '[No]'
  legally_allowed_to_work_in_canada: '[No]'
  requires_canada_sponsorship: '[Yes]'
  uk_work_authorization: '[No]'
  requires_uk_visa: '[Yes]'
  legally_allowed_to_work_in_uk: '[No]'
  requires_uk_sponsorship: '[Yes]'
work_preferences:
  remote_work: '[Yes]'
  in_person_work: '[Yes]'
  open_to_relocation: '[Yes]'
  willing_to_complete_assessments: '[Yes]'
  willing_to_undergo_drug_tests: '[Yes]'
  willing_to_undergo_background_checks: '[Yes]'
personal_information:
  name: Jeffrey
  surname: Rosenfeld
  date_of_birth: 10/06/1979
  country: United States
  city: Bergenfield
  address: 69 Wilbur Road
  zip_code: '07621'
  phone_prefix: jeffrey.rosenfeld@gmail.com
  phone: 917-664-8374
  email: jeffrey.rosenfeld@gmail.com
  linkedin: 'https://www.linkedin.com/in/jeffrosenfeld/'
education_details:
  - education_level: MBA
    institution: Rutgers University
    field_of_study: Business
    start_date: "2021"
    year_of_completion: "2024"
  - education_level: Doctoral Degree
    institution: NYU
    field_of_study: Biology
    start_date: "2005"
    year_of_completion: "2009'

experience_details:
  - position: 'Executive Director, Genomics and Bioinformatics'
    company: Tonix Pharmaceuticals
    employment_period: 2022-2024
    location: 'Chatham, NJ'
    industry: Pharmaceuticals
    key_responsibilities:
    - responsibility: "Managed team of Researchers and Consultants to perform Genome and Exome sequencing for clinical trials"
    - responsibility: "Planned, executed, and scaled research strategy"
    - responsibility: "Developed and implemented novel multi-marker GWAS algorithms for genome enhanced clinical trials"
    - responsibility: "Administered the Identification of genomic markers that predispose patients for fibromyalgia"
    - responsibility: "Oversaw the identification of 20 SNP pharmacogenomics panel to identify patients that will respond to therapy"
    - responsibility: "Presented results weekly to the CEO and CMO"
    - responsibility: "Sourced, selected, and managed vendors, consultants and Contract Research Organizations"
    
  - position: Associate Professor of Pathology – Precision Medicine
    company: Rutgers University - Cancer Institute of NJ
    employment_period: 2011-2022
    location: 'New Brunswick, NJ'
    industry: Laboratory Testing
    key_responsibilities:
    - responsibility_1: "Supervised a team of Researchers enabling genomics, cheminformatics and digital pathology"
    - responsibility_2: "Served as Bioinformatics Lead on implementation of 3 CLIA/CAP certified solid tumor and myeloid panels"
    - responsibility_3: "Handled all aspects of sequencing projects from experimental design through analysis, and publication"
    - responsibility_4: "Developed a Machine Learning model to predict the source organ of tumors of unknown origin"
    - responsibility_5: "Awarded $100k TechAdvance grant for single-ce'll sperm sequencing of families with autistic children"
    - responsibility_6: "Co-investigator or consultant on over $2M worth of grants from NIH and the Department of Defense"
    - responsibility_7: Managed Cancer Precision Medicine data from Foundation Medicine"
  - position: President
    company: Rosenfeld Consulting
    employment_period: 2013-present
    location: New Jersey
    industry: Consulting
    key_responsibilities:
    - responsibility_1: "Comapred the Economics of ambient storage and the use of freezers for nucleic acid storage"
    - responsibility_2: "Advised executive leadership by participating in hundreds of phone calls, providing insights on bioinformatics,genomics, lab testing, and precision medicine as well-regarded expert and KOL"
    - responsibility_3: "Provided technical due diligence and advised on $70M investment in MissionBio, among other investment"
    - responsibility_4: "Expert witness for the BRCA1 patent litigation, providing insights into genomic aspects of the litigation"
  - position: Research Scientist
    company: Northwell Health
    employment_period: 2009-2011
    location: 'Queens, NY'
    industry: Basic Research
    key_responsibilities:
    - responsibility_1: "Conducted analysis of GWAS and exome sequencing data for schizophrenia"
    - responsibility_2: "Designed and integrated a framework to identify multi-nucleotide polymorphisms in genomes
    - responsibility_3: Recipient of NARSAD Young Investigator Grant
languages:
  - language: English
    proficiency: Native

availability:
  notice_period: 2 weeks
self_identification:
  gender: '[Gender]'
  pronouns: '[Pronouns]'
  veteran: '[No]'
  disability: '[No]'
  ethnicity: '[Caucasian]'
legal_authorization:
  eu_work_authorization: '[No]'
  us_work_authorization: '[Yes]'
  requires_us_visa: '[No]'
  requires_us_sponsorship: '[Yes]'
  requires_eu_visa: '[Yes]'
  legally_allowed_to_work_in_eu: '[No]'
  legally_allowed_to_work_in_us: '[Yes]'
  requires_eu_sponsorship: '[Yes]'
  canada_work_authorization: '[No]'
  requires_canada_visa: '[No]'
  legally_allowed_to_work_in_canada: '[No]'
  requires_canada_sponsorship: '[Yes]'
  uk_work_authorization: '[No]'
  requires_uk_visa: '[Yes]'
  legally_allowed_to_work_in_uk: '[No]'
  requires_uk_sponsorship: '[Yes]'
work_preferences:
  remote_work: '[Yes]'
  in_person_work: '[Yes]'
  open_to_relocation: '[Yes]'
  willing_to_complete_assessments: '[Yes]'
  willing_to_undergo_drug_tests: '[Yes]'
  willing_to_undergo_background_checks: '[Yes]'
personal_information:
  name: Jeffrey
  surname: Rosenfeld
  date_of_birth: 10/06/1979
  country: United States
  city: Bergenfield
  address: 69 Wilbur Road
  zip_code: '07621'
  phone_prefix: jeffrey.rosenfeld@gmail.com
  phone: 917-664-8374
  email: jeffrey.rosenfeld@gmail.com
  linkedin: 'https://www.linkedin.com/in/jeffrosenfeld/'
education_details:
  - education_level: MBA
    institution: Rutgers University
    field_of_study: Business
    start_date: "2021"
    year_of_completion: "2024"
  - education_level: Doctoral Degree
    institution: NYU
    field_of_study: Biology
    start_date: "2005"
    year_of_completion: "2009'

experience_details:
  - position: 'Executive Director, Genomics and Bioinformatics'
    company: Tonix Pharmaceuticals
    employment_period: 2022-2024
    location: 'Chatham, NJ'
    industry: Pharmaceuticals
    key_responsibilities:
    - responsibility: "Managed team of Researchers and Consultants to perform Genome and Exome sequencing for clinical trials"
    - responsibility: "Planned, executed, and scaled research strategy"
    - responsibility: "Developed and implemented novel multi-marker GWAS algorithms for genome enhanced clinical trials"
    - responsibility: "Administered the Identification of genomic markers that predispose patients for fibromyalgia"
    - responsibility: "Oversaw the identification of 20 SNP pharmacogenomics panel to identify patients that will respond to therapy"
    - responsibility: "Presented results weekly to the CEO and CMO"
    - responsibility: "Sourced, selected, and managed vendors, consultants and Contract Research Organizations"
    
  - position: Associate Professor of Pathology – Precision Medicine
    company: Rutgers University - Cancer Institute of NJ
    employment_period: 2011-2022
    location: 'New Brunswick, NJ'
    industry: Laboratory Testing
    key_responsibilities:
    - responsibility_1: "Supervised a team of Researchers enabling genomics, cheminformatics and digital pathology"
    - responsibility_2: "Served as Bioinformatics Lead on implementation of 3 CLIA/CAP certified solid tumor and myeloid panels"
    - responsibility_3: "Handled all aspects of sequencing projects from experimental design through analysis, and publication"
    - responsibility_4: "Developed a Machine Learning model to predict the source organ of tumors of unknown origin"
    - responsibility_5: "Awarded $100k TechAdvance grant for single-ce'll sperm sequencing of families with autistic children"
    - responsibility_6: "Co-investigator or consultant on over $2M worth of grants from NIH and the Department of Defense"
    - responsibility_7: Managed Cancer Precision Medicine data from Foundation Medicine"
  - position: President
    company: Rosenfeld Consulting
    employment_period: 2013-present
    location: New Jersey
    industry: Consulting
    key_responsibilities:
    - responsibility_1: "Comapred the Economics of ambient storage and the use of freezers for nucleic acid storage"
    - responsibility_2: "Advised executive leadership by participating in hundreds of phone calls, providing insights on bioinformatics,genomics, lab testing, and precision medicine as well-regarded expert and KOL"
    - responsibility_3: "Provided technical due diligence and advised on $70M investment in MissionBio, among other investment"
    - responsibility_4: "Expert witness for the BRCA1 patent litigation, providing insights into genomic aspects of the litigation"
  - position: Research Scientist
    company: Northwell Health
    employment_period: 2009-2011
    location: 'Queens, NY'
    industry: Basic Research
    key_responsibilities:
    - responsibility_1: "Conducted analysis of GWAS and exome sequencing data for schizophrenia"
    - responsibility_2: "Designed and integrated a framework to identify multi-nucleotide polymorphisms in genomes
    - responsibility_3: Recipient of NARSAD Young Investigator Grant
languages:
  - language: English
    proficiency: Native

availability:
  notice_period: 2 weeks
self_identification:
  gender: '[Gender]'
  pronouns: '[Pronouns]'
  veteran: '[No]'
  disability: '[No]'
  ethnicity: '[Caucasian]'
legal_authorization:
  eu_work_authorization: '[No]'
  us_work_authorization: '[Yes]'
  requires_us_visa: '[No]'
  requires_us_sponsorship: '[Yes]'
  requires_eu_visa: '[Yes]'
  legally_allowed_to_work_in_eu: '[No]'
  legally_allowed_to_work_in_us: '[Yes]'
  requires_eu_sponsorship: '[Yes]'
  canada_work_authorization: '[No]'
  requires_canada_visa: '[No]'
  legally_allowed_to_work_in_canada: '[No]'
  requires_canada_sponsorship: '[Yes]'
  uk_work_authorization: '[No]'
  requires_uk_visa: '[Yes]'
  legally_allowed_to_work_in_uk: '[No]'
  requires_uk_sponsorship: '[Yes]'
work_preferences:
  remote_work: '[Yes]'
  in_person_work: '[Yes]'
  open_to_relocation: '[Yes]'
  willing_to_complete_assessments: '[Yes]'
  willing_to_undergo_drug_tests: '[Yes]'
  willing_to_undergo_background_checks: '[Yes]'
: "Developed and implemented novel multi-marker GWAS algorithms for genome enhanced clinical trials"
    - responsibility_4: "Administered the Identification of genomic markers that predispose patients for fibromyalgia"
    - responsibility_5: "Oversaw the identification of 20 SNP pharmacogenomics panel to identify patients that will respond to therapy"
    - responsibility_6: "Presented results weekly to the CEO and CMO"
    - responsibility_7: "Sourced, selected, and managed vendors, consultants and Contract Research Organizations"
  - position: Associate Professor of Pathology – Precision Medicine
    company: Rutgers University - Cancer Institute of NJ
    employment_period: 2011-2022
    location: 'New Brunswick, NJ'
    industry: Laboratory Testing
    key_responsibilities:
    - responsibility_1: "Supervised a team of Researchers enabling genomics, cheminformatics and digital pathology"
    - responsibility_2: "Served as Bioinformatics Lead on implementation of 3 CLIA/CAP certified solid tumor and myeloid panels"
    - responsibility_3: "Handled all aspects of sequencing projects from experimental design through analysis, and publication"
    - responsibility_4: "Developed a Machine Learning model to predict the source organ of tumors of unknown origin"
    - responsibility_5: "Awarded $100k TechAdvance grant for single-ce'll sperm sequencing of families with autistic children"
    - responsibility_6: "Co-investigator or consultant on over $2M worth of grants from NIH and the Department of Defense"
    - responsibility_7: Managed Cancer Precision Medicine data from Foundation Medicine"
  - position: President
    company: Rosenfeld Consulting
    employment_period: 2013-present
    location: New Jersey
    industry: Consulting
    key_responsibilities:
    - responsibility_1: "Comapred the Economics of ambient storage and the use of freezers for nucleic acid storage"
    - responsibility_2: "Advised executive leadership by participating in hundreds of phone calls, providing insights on bioinformatics,genomics, lab testing, and precision medicine as well-regarded expert and KOL"
    - responsibility_3: "Provided technical due diligence and advised on $70M investment in MissionBio, among other investment"
    - responsibility_4: "Expert witness for the BRCA1 patent litigation, providing insights into genomic aspects of the litigation"
  - position: Research Scientist
    company: Northwell Health
    employment_period: 2009-2011
    location: 'Queens, NY'
    industry: Basic Research
    key_responsibilities:
    - responsibility_1: "Conducted analysis of GWAS and exome sequencing data for schizophrenia"
    - responsibility_2: "Designed and integrated a framework to identify multi-nucleotide polymorphisms in genomes
    - responsibility_3: Recipient of NARSAD Young Investigator Grant
languages:
  - language: English
    proficiency: Native

availability:
  notice_period: 2 weeks
self_identification:
  gender: '[Gender]'
  pronouns: '[Pronouns]'
  veteran: '[No]'
  disability: '[No]'
  ethnicity: '[Caucasian]'
legal_authorization:
  eu_work_authorization: '[No]'
  us_work_authorization: '[Yes]'
  requires_us_visa: '[No]'
  requires_us_sponsorship: '[Yes]'
  requires_eu_visa: '[Yes]'
  legally_allowed_to_work_in_eu: '[No]'
  legally_allowed_to_work_in_us: '[Yes]'
  requires_eu_sponsorship: '[Yes]'
  canada_work_authorization: '[No]'
  requires_canada_visa: '[No]'
  legally_allowed_to_work_in_canada: '[No]'
  requires_canada_sponsorship: '[Yes]'
  uk_work_authorization: '[No]'
  requires_uk_visa: '[Yes]'
  legally_allowed_to_work_in_uk: '[No]'
  requires_uk_sponsorship: '[Yes]'
work_preferences:
  remote_work: '[Yes]'
  in_person_work: '[Yes]'
  open_to_relocation: '[Yes]'
  willing_to_complete_assessments: '[Yes]'
  willing_to_undergo_drug_tests: '[Yes]'
  willing_to_undergo_background_checks: '[Yes]'

(virtual) jeffrey@Jeffreys-Laptop Auto_Jobs_Applier_AIHawk % python main.py          
2024-10-29 13:29:07.563 | ERROR    | __main__:main:219 - Runtime error: Error running the bot: Error parsing YAML file.

(virtual) jeffrey@Jeffreys-Laptop Auto_Jobs_Applier_AIHawk % python main.py --resume ~/Dropbox/test/Rosenfeld_Resume.pdf
2024-10-29 13:28:56.766 | ERROR    | __main__:main:219 - Runtime error: Error running the bot: Error parsing YAML file.
[plain_text_resume.yaml.txt](https://github.com/user-attachments/files/17560936/plain_text_resume.yaml.txt)

### Expected behavior

The bot should run

### Actual behavior

Bot crashed

### Branch

None

**Comment by FrancescoVassalli** [comment]
There is probably some issue with the formatting in the yaml file. You may be able to use a tool like this to find the issue 

https://jsonformatter.org/yaml-formatter

**Comment by ibrahimhaleemkhan** [comment]
I am getting a parse issue, have formatted the YAML too. 

ERROR    | __main__:main:219 - Runtime error: Error running the bot: Unexpected error while parsing YAML: 1 validation error for Resume
education_details.0.year_of_completion
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='12/01/2023', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing

**Comment by siddharthp30** [comment]
Same issue

**Comment by FrancescoVassalli** [comment]
> Same issue, tried the yaml formatter as well

Please make a new issue with the specific error message you get
