### ISSUE TITLE
[FEATURE]: Better job blacklisting (Title, Location)

### ISSUE THREAD

**Issue by Jasar-k** [AIHawk-co/Auto_Jobs_Applier#667]
### Feature summary

Make title/location blacklisting better with better string matching or make it gpt powered

### Feature description

The current blacklisting is direct matching with the configuration file. This introduces multiple false positives.
Examples: 
"Brazil" is blacklisted, but "Rio de Janeiro, Brazil", is whitelisted as false positive
"Data Engineer" is blacklisted ,but "Data Engineer(Gen AI)" is whitelisted as false positive

Solution: introduce better-matching algo or make blacklisting GPT powered

### Motivation

Better blacklisting makes the applied jobs more relevant

### Alternatives considered

Instead of direct string matching, split it first, then check. 
Long-term solution: make a comprehensive string parsing which handles all non-text characters

Comprehensive (Not efficient) solution: Make a check with GPT

**Comment by GuilhermeRameh** [comment]
Hi @Jasar-k , can i work on this?
Im thinking on using regex for this

**Comment by Jasar-k** [comment]
Yes please do, I do have a gpt based solution which I am using but an efficient solution would be nice
