### ISSUE TITLE
Configuration error: Invalid distance value in config file data_folder\config.yaml. Must be one of: {0, 50, 100, 5, 25, 10}

### ISSUE THREAD

**Issue by Aditya2179** [AIHawk-co/Auto_Jobs_Applier#687]
### Describe the bug

I am facing issue while running Python main.py and it gives me an invalid distance error

### Expected behavior

this was the final step before log in to Linked in for bot to apply jobs

### Actual behavior

Resulted in the invalid distance bug

### Branch

None

### Python version

3.11.4

### LLM Used

Ollama

### Model used

llama3.2

**Comment by 49Simon** [comment]
What is the `distance` value you have in your config.yaml file?

**Comment by Aditya2179** [comment]
how do I measure distance value in the config yaml file

**Comment by Aditya2179** [comment]
I think I am stuck in the last step running Python main.py in the BOT directory C:\Users\radhi\LinkedIn_AIHawk_automatic_job_application>

**Comment by Aditya2179** [comment]
I think I got stuck in the last step running the python main.py in the below cd
LinkedIn_AIHawk_automatic_job_application>

**Comment by RishuCod** [comment]
in the config you have to choose the value of the distance from {0, 50, 100, 5, 25, 10}
e.g.-
apply_once_at_company: true

distance: 100(this one in the config file )
it gives error if you gave value other than that.


> ### Describe the bug
> I am facing issue while running Python main.py and it gives me an invalid distance error
> 
> ### Steps to reproduce
> _No response_
> 
> ### Expected behavior
> this was the final step before log in to Linked in for bot to apply jobs
> 
> ### Actual behavior
> Resulted in the invalid distance bug
> 
> ### Branch
> None
> 
> ### Branch name
> _No response_
> 
> ### Python version
> 3.11.4
> 
> ### LLM Used
> Ollama
> 
> ### Model used
> llama3.2
> 
> ### Additional context
> _No response_

in the config you have to choose the value of the distance from {0, 50, 100, 5, 25, 10}
e.g.-
apply_once_at_company: true

distance: 100(this one in the config file )
it gives error if you gave value other than that.

**Comment by RishuCod** [comment]
> how do I measure distance value in the config yaml file

you don't have to, you just have to choose the value from the option given.

**Comment by Aditya2179** [comment]
hi I have choosen the value of 100 as you suggested, but still the same error

**Comment by Aditya2179** [comment]
![image](https://github.com/user-attachments/assets/36b14f25-4789-46dd-a02b-9e505ddb11a4)

**Comment by 49Simon** [comment]
If you have `distance`: 100, you should not get the same error. If you still do, make sure your yaml file is not corrupted.

**Comment by Aditya2179** [comment]
ok How do I make sure about that, can we do screen share or can I post the yaml file over here so that we debug this, its going on for a while really need an urgent help on this

**Comment by Aditya2179** [comment]
there is M letter I can see next to the file name in VSC code, not sure how do I interpret this?

**Comment by 49Simon** [comment]
Join discord here: https://discord.gg/T3reeuUU

**Comment by Aditya2179** [comment]
ok Joined

**Comment by FrancescoVassalli** [comment]
Can this be closed?
