### ISSUE TITLE
[BUG]: Don't save job specific answers

### ISSUE THREAD

**Issue by sloganking** [AIHawk-co/Auto_Jobs_Applier#690]
### Steps to reproduce

Some answers saves to `answers.json` are responding to a specific employer. This is good in that the bot tailors its answers to specific companies. However this means that retrieving the same answer for the same question again is often inappropriate. As one company will receive a message specifically tailored to a different company and mentioning the other company's name. 

### Expected behavior

The bot should not remember answers that are company-specific. 

### Actual behavior

The bot gives company-specific answers to their own company. 

### Branch

None

**Comment by sloganking** [comment]
https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/commit/33f182631e857a9bc8fe94239394e9aa4377a6f5 This commit attempted to fix this issue before. However as seen in https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/612#issuecomment-2439794896 @cjbbb ...said it introduced an issue, and it was reverted. However https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/commit/33f182631e857a9bc8fe94239394e9aa4377a6f5 may still provide inspiration for how to fix this.

**Comment by FrancescoVassalli** [comment]
Ok making a fix for this

**Comment by FrancescoVassalli** [comment]
Can you close this since my fix is merged?
