### ISSUE TITLE
[HELP WANTED]: <Provide a descriptive title>

### ISSUE THREAD

**Issue by PiyushYadav19** [AIHawk-co/Auto_Jobs_Applier#700]
### Issue description

HI Try to run a program but got these error .
python main.py
Configuration error: Missing or invalid key 'remote' in config file data_folder\config.yaml
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
education_details.0.year_of_completion
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='[Year of Completion]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
projects.0.link
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
projects.1.link
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

### Specific tasks

Runtime Env

**Comment by btgendler2005** [comment]
Can you share your config?

**Comment by PiyushYadav19** [comment]
[Config File.zip](https://github.com/user-attachments/files/17605425/Config.File.zip)
HI @btgendler2005  here is the config .

**Comment by feder-cr** [comment]
@PiyushYadav19 @akashbilgi @btgendler2005  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
