### ISSUE TITLE
[FEATURE]: Job Suitability Const

### ISSUE THREAD

**Issue by FrancescoVassalli** [AIHawk-co/Auto_Jobs_Applier#705]
### Feature summary

 Job Suitability Const

### Feature description

Instead of hard coding the job suitability requirement to 7, I'll change it to a const in the appconfig which will allow users to set this how they like

### Motivation

tunability

### Alternatives considered

I think this already is the alternative to https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/669

This could be a command line arg instead but I think with too many command line args we are just going to clutter the whole thing.

**Comment by surapuramakhil** [comment]
keep this open likewise mentioned in other comment.
