### ISSUE TITLE
[FEATURE]: Ability to answer custom questions

### ISSUE THREAD

**Issue by sdpa** [AIHawk-co/Auto_Jobs_Applier#719]
### Feature summary

Answer custom questions using a LLM

### Feature description

The bot often skips questions that are probably custom to the job posting and skips applying to those jobs, resulting in filtering a lot of potential jobs. Therefore, as part of the workflow, for custom  questions, or questions that have not been encountered before, the bot will ask the LLM for the answer, It can provide additional details like the answer format, is it free text, checkbox, drop down select, multi select, etc. The resume will also be submitted as context. 

### Motivation

Make the bot more robust

**Comment by FrancescoVassalli** [comment]
I think this is how it already works. Are you sure you are on the most recent version ?
