### ISSUE TITLE
[BUG]: Logging error in Loguru Handler

### ISSUE THREAD

**Issue by Pointfit** [AIHawk-co/Auto_Jobs_Applier#762]
### Describe the bug

Logging error in Loguru Handler

### Steps to reproduce

![permission_error](https://github.com/user-attachments/assets/542f4b17-033d-414b-a693-238f49483c77)

2024-11-05 10:23:57.852 | DEBUG    | src.utils:scroll_slow:80 - Scrolled to position: 1227
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1269, microseconds=299411), 'exception': None, 'extra': {}, 'file': (name='utils.py', path='<censored>\Auto_Jobs_Applier_AIHawk\\src\\utils.py'), 'function': 'scroll_slow', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 80, 'message': 'Scrolled to position: 977', 'module': 'utils', 'name': 'src.utils', 'process': (id=12276, name='MainProcess'), 'thread': (id=16132, name='MainThread'), 'time': datetime(2024, 11, 5, 10, 23, 58, 650171, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600), 'Pacific Standard Time'))}
Traceback (most recent call last):
  File "<censored>\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\loguru\_handler.py", line 206, in emit
    self._sink.write(str_record)
  File "<censored>\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\loguru\_file_sink.py", line 204, in write
    self._terminate_file(is_rotating=True)
  File "<censored>\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\loguru\_file_sink.py", line 276, in _terminate_file
    os.rename(old_path, renamed_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '<censored>\Auto_Jobs_Applier_AIHawk\\log\\app.log' -> '<censored>\Auto_Jobs_Applier_AIHawk\\log\\app.2024-11-05_10-02-49_225424.log'
--- End of logging error ---

It was working fine yesterday. I don't think it's affecting functionality. Not sure though.

I even tried deleting the entire log file to see if its size was the issue. It created a new log and still caused this error.

### Expected behavior

No logging errors.

### Actual behavior

Logging errors

### Branch

None

### LLM Used

OpenAI

### Model used

gpt-4o-mini

### Additional context

Temporary solution/work around is to disable file logging
https://github.com/AIHawk-app/Auto_Jobs_Applier/issues/762#issuecomment-2460452364

_No response_

**Comment by Damffer** [comment]
I have the same issue

**Comment by feder-cr** [comment]
I have the same issue @sarob @surapuramakhil @sarob

**Comment by surapuramakhil** [comment]
it clearly looks like an access issue to me. not code issue, "might also be file lock issues"

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\Auto_Jobs_Applier_AIHawk\log\app.log' -> '\Auto_Jobs_Applier_AIHawk\log\app.2024-11-05_10-02-49_225424.log'

@feder-cr have started running it from multiple terminals? I am pretty sure code is not thread safe or supporting concurrent access of resources like files.

Since it's a file lock issue, have you tried restarting your pc and still weather if lock is still getting acquired?

Also, the log file is opened by any application. like vs code or any text editor - if so, kindly don't do it while bot is running.

**Comment by Pointfit** [comment]
I am not threading it.
I have tried restarting PC.
And the log file is NOT open by any editor.

Issue still happening.

**Comment by surapuramakhil** [comment]
@Pointfit is it exiting Application or skipping that particular job application?

**Comment by Pointfit** [comment]
@surapuramakhil no, it can still fill out an application with this error.

**Comment by mbilal3** [comment]
I'm getting the same error message. My cv autogeneration won't too. It is using the same cv to apply to every job. Although, I'm using the python main.py command. Any resolution to this would be greatly appreciated. Thanks

<img width="959" alt="error" src="https://github.com/user-attachments/assets/155cb390-798f-4878-a24c-60900294e217">

**Comment by surapuramakhil** [comment]
Until this bug gets fixed you can disable file logging by setting this to false. logging config

https://github.com/AIHawk-app/Auto_Jobs_Applier/blob/0fd49db4d6bab364f1f5dbe18b79e6f5ba5051a4/app_config.py#L7

**Comment by U-C4N** [comment]
done , pushed

**Comment by mbilal3** [comment]
> Until this bug gets fixed you can disable file logging by setting this to false. logging config
> 
> https://github.com/AIHawk-app/Auto_Jobs_Applier/blob/0fd49db4d6bab364f1f5dbe18b79e6f5ba5051a4/app_config.py#L7

This does make the error message go away. Thank you.

Also, the bot does not generate any custom job tailored resumes for me. Is it because of this error or there might be a different issue?

**Comment by alanzhangithub** [comment]
> Until this bug gets fixed you can disable file logging by setting this to false. logging config
> 
> https://github.com/AIHawk-app/Auto_Jobs_Applier/blob/0fd49db4d6bab364f1f5dbe18b79e6f5ba5051a4/app_config.py#L7

This fixes the problems encountered. 
I ran into this problem when using the --resume option.

**Comment by feder-cr** [comment]
Fixed!
