### ISSUE TITLE
Configuration Error: Missing or Invalid Key 'experience_level' in config.yaml

### ISSUE THREAD

**Issue by SirTypeOfficial** [AIHawk-co/Auto_Jobs_Applier#767]
### Describe the bug

I encountered the error "Missing or invalid key 'experience_level' in config file data_folder\config.yaml" while running the program.

### Steps to reproduce

Downloaded and extracted the project from GitHub.

Updated the config.yaml file with my own settings.

python -m venv virtual

.\virtual\Scripts\activate

pip install -r requirements.txt

python main.py --collect

2024-11-06 05:46:22.663 | ERROR    | __main__:main:221 - Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk?tab=readme-ov-file#configuration Missing or invalid key 'experience_level' in config file data_folder\config.yaml    

![Screenshot 2024-11-06 055744](https://github.com/user-attachments/assets/27977003-c5a0-4a17-a98e-235d8f2c2974)

this is my config file picture.

**Comment by 49Simon** [comment]
This issue has been fixed and will be merged to main in the next release. Meanwhile, you can use the `release/v11.15.2024` branch for the updated code.

**Comment by pedrovs16** [comment]
all the fields should use snake_cases so: experience_level, job_types, full_time ....
