### ISSUE TITLE
[BUG]: Not Using Default Resume with OpenAI APi

### ISSUE THREAD

**Issue by Issac-Kondreddy** [AIHawk-co/Auto_Jobs_Applier#770]
### Describe the bug

Even though I give --resume "Resume.pdf" it is still asking me to select resumes provided by application

### Steps to reproduce

<img width="667" alt="Screenshot 2024-11-06 at 9 54 37 PM" src="https://github.com/user-attachments/assets/3511a686-7591-41be-a15b-1c07a4356bd9">

### Branch

main

### Model used

GPT-4o

**Comment by cjbbb** [comment]
Could you please try the new "main branch". Fetch the new coding and try again. Since it should be solved with commits  [#a6da7828ebde1b6d8a972cc5b90eb758f44dbead](https://github.com/AIHawk-co/Auto_Jobs_Applier/commit/a6da7828ebde1b6d8a972cc5b90eb758f44dbead)
