### ISSUE TITLE
[FEATURE]: Is it me or this program runs too slow

### ISSUE THREAD

**Issue by mrtknrt** [AIHawk-co/Auto_Jobs_Applier#774]
### Feature description

 Is it me or this program runs too slow, if you run a whole the max number of job it will apply will be 20 maybe. How can we increase the speed?

**Comment by akashbilgi** [comment]
Its is scpaced out to avoid bot like behaviour on linkedIn..
has been answered before

**Comment by akashbilgi** [comment]
https://github.com/AIHawk-co/Auto_Jobs_Applier/issues/613#issue-2615560081
