### ISSUE TITLE
[BUG]: Getting "Runtime error: Error running the bot: module 'src.utils' has no attribute 'printyellow'" when using collect mode

### ISSUE THREAD

**Issue by vabichequer** [AIHawk-co/Auto_Jobs_Applier#783]
### Describe the bug

When using the tool with the collect mode, "Runtime error: Error running the bot: module 'src.utils' has no attribute 'printyellow'" occurs. On the normal mode, it doens't.

### Steps to reproduce

Using latest version on the main branch, as v2024.11.07.

run the program with 'python main.py --collect'

### Expected behavior

Have the program collect data

### Actual behavior

Error is returned

### Branch

main

### Python version

3.12.5

### LLM Used

ChatGPT

### Model used

GPT-4o-mini

**Comment by surapuramakhil** [comment]
@vabichequer would you like to work on it? just comment on those lines. PrintYellow will be replaced with logger later
