### ISSUE TITLE
[BUG]:  While generating resume through gemini getting error  

### ISSUE THREAD

**Issue by surajmoolya** [AIHawk-co/Auto_Jobs_Applier#791]
### Describe the bug

while generating resume throght gemin it is hitting open ai api

### Steps to reproduce

creating resume using gemini

### Expected behavior

create a resume

### Actual behavior

failed, was trying to create api through openai

### Branch

None

### LLM Used

Gemin

### Model used

gemini-1.5-flash-latest

### Additional context

![image](https://github.com/user-attachments/assets/2c693cd6-1c38-4e8d-b29f-ea76a23b73f6)

**Comment by surapuramakhil** [comment]
@surajmoolya I believe it's making call to open AI. It's a different project

https://github.com/feder-cr/lib_resume_builder_AIHawk
